import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

class CuriosityPage extends HookWidget {
  final List<String> facts = [
    "🌪️ Tornado może osiągnąć prędkość wiatru do 500 km/h.",
    "❄️ Najniższa temperatura na Ziemi to -89,2°C (Antarktyda, 1983).",
    "☀️ Słońce odpowiada za wszystkie zjawiska pogodowe na Ziemi.",
    "🌈 Tęcza tworzy pełne koło, ale widzimy tylko pół.",
    "💧 Wilgotność powietrza wpływa na nasze odczucie temperatury.",
    "⚡ Piorun ma temperaturę wyższą niż powierzchnia Słońca – do 30 000°C.",
    "🌫️ Mgła to chmura dotykająca ziemi.",
    "🌍 Pogoda na równiku jest mniej zmienna niż na biegunach.",
    "🌀 Front atmosferyczny to granica między masami powietrza.",
    "🌧️ Deszcz potrafi zawierać pył, sól, a nawet popiół wulkaniczny.",
    "🌬️ Wiatr powstaje przez różnice ciśnienia w atmosferze.",
    "🌨️ Śnieg może wystąpić nawet powyżej 0°C.",
    "🌊 Huragany zasilane są przez ciepło oceaniczne.",
    "🧊 Grad to krople wielokrotnie zamrażane w chmurze.",
    "🌪️ Tornada najczęściej występują w Aleji Tornad w USA.",
    "🌡️ Najwyższa temperatura: 56.7°C (Kalifornia, 1913).",
    "👃 Zapach deszczu to 'geosmina' – związek chemiczny wydzielany przez bakterie.",
    "⛈️ Najwięcej burz rocznie jest w Ugandzie i Kongu.",
    "🌬️ Halny w Polsce może wywołać bóle głowy i drażliwość.",
    "❄️ Każdy płatek śniegu ma unikalny kształt.",
    "☁️ Chmury cumulonimbus sięgają 20 km w górę.",
    "🌞 Na biegunie słońce potrafi nie zachodzić przez 6 miesięcy.",
    "🚗 Tornado może unieść samochód.",
    "🌫️ Mgła ogranicza widoczność do poniżej 1 km.",
    "🌈 Możliwa jest podwójna tęcza z odwrotnymi kolorami.",
    "🌩️ Piorun może rozszczepiać drzewo w ułamku sekundy.",
    "🧊 Szron powstaje z pary wodnej bezpośrednio zamrożonej.",
    "🌦️ Pogoda zmienia się lokalnie – to mikroklimat.",
    "🌐 El Niño wpływa na pogodę na całym świecie.",
    "🌀 Cyklony mogą mieć szerokość ponad 1000 km.",
    "🌤️ Pogoda wpływa na samopoczucie i senność.",
    "🌈 Tęcze mogą wystąpić także nocą – tzw. 'moonbow'.",
    "🛫 Wiatr zmienia kursy lotów i czas przelotu.",
    "🌫️ Mgła morska tworzy się nad ciepłą wodą.",
    "🌍 W pustyniach również może padać śnieg!",
    "☁️ Lentikularne chmury wyglądają jak UFO.",
    "📡 Pogodę obserwują specjalne satelity meteorologiczne.",
    "🧭 Efekt Coriolisa sprawia, że cyklony kręcą się w różne strony.",
    "🌞 Najdłuższy dzień na północy trwa ponad 20 godzin.",
    "🌬️ Wiatr może zrywać dachy i przewracać drzewa.",
    "☔ Deszcz w dżungli bywa codzienny i punktualny.",
    "🌈 Z samolotu można zobaczyć pełną, okrągłą tęczę.",
    "🔥 Pył z Sahary może dotrzeć aż do Europy.",
    "🌪️ Tornada klasy F5 niszczą wszystko na swojej drodze.",
    "🌧️ Deszcz może być kolorowy – różowy, czerwony, żółty.",
    "🌊 Monsun przynosi życiodajne deszcze w Azji.",
    "⏱️ Pogoda może zmienić się w kilka minut.",
    "🌨️ Śnieg wygłusza dźwięki – dlatego zimą jest ciszej.",
    "🌍 Pogoda była kluczowa np. w bitwie pod Waterloo.",
    "🛰️ Pogoda kosmiczna wpływa na GPS i komunikację.",
    "🌫️ Smog to mgła z zanieczyszczeniami.",
    "☀️ Promienie UV mogą przenikać cienkie chmury.",
    "📏 Grad może mieć średnicę piłki tenisowej.",
    "🌊 Tsunami może być poprzedzone cofnięciem morza.",
    "❄️ Lodowce tworzą się przez setki lat.",
    "💨 Silny wiatr może przewrócić ciężarówkę.",
    "🌦️ Pogoda jest najczęściej sprawdzaną informacją w telefonach.",
    "☁️ Altostratus to chmura średniego piętra.",
    "🧊 W zimie lód izoluje jeziora przed dalszym zamarzaniem.",
    "🌡️ Punkt rosy określa moment skraplania się pary wodnej.",
    "🌨️ Opady mogą być tak silne, że w minutę spadnie 20 mm.",
    "💧 Kropla deszczu nie jest kształtu łezki – to raczej spłaszczona kula.",
    "🌈 Czasem można zobaczyć 3 lub więcej tęcz naraz.",
    "🧪 Woda z deszczu może mieć pH kwaśne lub zasadowe.",
    "📉 Barometr mierzy zmiany ciśnienia atmosferycznego.",
    "🌬️ Wiatry lokalne mają własne nazwy – jak 'bora' czy 'sirocco'.",
    "⚠️ Burza piaskowa może zablokować całe miasta.",
    "🧤 Przy -30°C odmrożenia mogą wystąpić po kilku minutach.",
    "🌈 Tęcze powstają dzięki rozszczepieniu światła w kroplach.",
    "🌨️ Istnieje 'śnieg z nieba bez chmur' – np. przy inwersji.",
    "🌪️ Tornado może trwać tylko 30 sekund.",
    "☁️ Chmury stratocumulus pokrywają całe niebo w fale.",
    "☀️ Pogoda na Wenus jest bardziej ekstremalna niż na Ziemi.",
    "🌙 W zimne, bezchmurne noce jest zimniej niż w pochmurne.",
    "🎯 W centrum cyklonu panuje cisza – to tzw. oko cyklonu.",
    "🌧️ Deszczowy dzień może oznaczać tylko kilka minut opadu.",
    "🌡️ Zjawisko 'zimnej kropli' przynosi nagłe burze latem.",
    "📶 Pogoda wpływa na zasięg i jakość sygnału radiowego.",
    "🌤️ Promieniowanie słoneczne ogrzewa powierzchnię – nie powietrze.",
    "📷 Piorun może mieć długość kilku kilometrów.",
    "🧼 Zimą zanieczyszczenia częściej zalegają przy gruncie.",
    "☁️ W chmurach może się znajdować nawet 1 mln litrów wody.",
    "🌨️ Śnieg może mieć różne barwy, np. niebieskawy w górach.",
    "☔ W czasie deszczu temperatura może spaść o kilka stopni w minutę.",
    "🌀 Cyklony mogą występować również na Marsie!",
    "🌦️ 'Słoneczny deszcz' to częsty efekt frontów przejściowych.",
    "🧊 Szron potrafi tworzyć misterne, geometryczne struktury.",
    "🌫️ Mgła lodowa to groźne zjawisko dla lotnictwa.",
    "🔔 Zmiany ciśnienia mogą wpływać na ból głowy.",
    "📡 Meteorolodzy stosują balony pogodowe codziennie na całym świecie.",
    "🌍 Nie ma dwóch identycznych zjawisk pogodowych – każde jest unikatowe!",
    "🌧️ Deszcz pada z chmur o wysokości nawet 10 km.",
    "🌩️ Pioruny uderzają Ziemię ok. 100 razy na sekundę.",
    "🌨️ W Norwegii śnieg może zalegać przez 6 miesięcy w roku.",
    "🔥 W Kalifornii pogoda sprzyja powstawaniu pożarów przez większość roku.",
    "🌈 Tęcze są częstsze w krajach tropikalnych niż umiarkowanych.",
    "🌫️ Mgła w dolinach potrafi utrzymywać się cały dzień.",
    "🧊 Lodowce magazynują ponad 75% słodkiej wody na świecie.",
    "🌊 Fale upałów zabijają więcej ludzi niż huragany czy powodzie.",
    "🧭 Pogoda była kluczowa w planowaniu lądowania w Normandii.",
    "☁️ Chmury mogą ważyć miliony ton, mimo że unoszą się w powietrzu.",
    "🌬️ Wiatr fenowy może nagle podnieść temperaturę o 15°C.",
    "🌦️ Pogoda potrafi zmieniać się z minuty na minutę w górach.",
    "❄️ Śnieżynki tworzą się z mikroskopijnych cząsteczek pyłu.",
    "🌪️ Największe tornado miało średnicę ponad 4 km.",
    "📡 Stacje pogodowe zbierają dane nawet co 5 minut.",
    "📷 Piorun może być widoczny z odległości 100 km.",
    "🧊 Antarktyda jest jednocześnie najsuchszym i najzimniejszym kontynentem.",
    "🌡️ Termometr Galileusza wykorzystuje zasady wyporności.",
    "🌀 Cyklony tropikalne powstają tylko nad ciepłymi wodami oceanów.",
    "🌧️ Opady atmosferyczne mogą zawierać mikroplastik.",
    "🌈 Najdłużej utrzymująca się tęcza trwała 9 godzin!",
    "💧 Rosa tworzy się, gdy powierzchnia jest chłodniejsza niż powietrze.",
    "❄️ Śnieg może izolować od zimna — dlatego igloo utrzymuje ciepło.",
    "🌀 Huragany na półkuli północnej kręcą się przeciwnie do wskazówek zegara.",
    "📈 Barometry rtęciowe to jedne z najstarszych narzędzi meteorologicznych.",
    "🌫️ Inwersja termiczna zatrzymuje zanieczyszczenia przy gruncie.",
    "☀️ Latem powietrze może wydawać się cięższe przez wysoką wilgotność.",
    "📦 Pogoda może zakłócać łańcuchy dostaw i transport lotniczy.",
    "🧊 Grad to efekt intensywnych prądów wznoszących w chmurze burzowej.",
    "💨 Wiatry na Jowiszu przekraczają 600 km/h.",
    "🌩️ Piorun kulisty to rzadkie i tajemnicze zjawisko atmosferyczne.",
    "🌡️ Termometr alkoholowy działa lepiej przy niskich temperaturach.",
    "🌦️ Pory deszczowe występują w cyklach monsunowych.",
    "🌪️ Tornado może przemieszczać się z prędkością 100 km/h.",
    "🌊 Pogoda oceaniczna jest bardziej stabilna niż kontynentalna.",
    "📡 Satelity pogodowe krążą wokół Ziemi co 90 minut.",
    "🌫️ Mgła może zawierać zanieczyszczenia z fabryk i samochodów.",
    "❄️ Płatki śniegu mogą mieć nawet 30 ramion.",
    "☀️ Słońce świeci nad Ziemią średnio przez 12 godzin dziennie.",
    "💧 Chmury tworzą się, gdy powietrze osiągnie punkt rosy.",
    "⚡ Pioruny najczęściej uderzają w wysokie budynki i drzewa.",
    "🌡️ Temperatura odczuwalna zależy od wiatru i wilgotności.",
    "🌬️ Wiatr może być efektem lokalnym lub globalnym (pasaty).",
    "🌦️ W górach pogoda może zmieniać się co kilkanaście minut.",
    "🌩️ Grom dźwiękowy podąża po błyskawicy — z opóźnieniem.",
    "🧪 Meteorologia korzysta z fizyki, chemii i matematyki.",
    "🌪️ Tornado może wciągnąć wodę z jeziora i utworzyć wodospad.",
    "🧤 W niskiej temperaturze ciecz może zamarznąć w ciągu sekundy.",
    "🌍 Efekt cieplarniany to naturalne zjawisko niezbędne do życia.",
    "☁️ Wysokość chmur określa się za pomocą lidarów lub balonów.",
    "🌈 Kolory tęczy to zawsze ten sam układ: czerwony do fioletu.",
    "🌨️ Opady śniegu mogą występować nawet przy +2°C.",
    "🌬️ Wiatr halny to ciepły i suchy wiatr z gór.",
    "🌦️ Chmury piętra średniego to altostratus i altocumulus.",
    "🌩️ Pioruny często występują na granicy frontów chłodnych.",
    "🧊 Grad może powstać nawet latem przy intensywnej burzy.",
    "💨 Wiatry katabatyczne schodzą z gór z dużą siłą.",
    "🌫️ Mgła radiacyjna powstaje w bezwietrzne, chłodne noce.",
    "☀️ Indeks UV określa siłę promieniowania ultrafioletowego.",
    "🌊 Burze tropikalne mogą prowadzić do powodzi błyskawicznych.",
    "🌡️ Inwersja temperatury powoduje stagnację powietrza.",
    "🌩️ Piorun może uderzyć kilka razy w to samo miejsce.",
    "🧊 Lód morski wpływa na klimat całej planety.",
    "📷 Kamery meteorologiczne pomagają w monitoringu zjawisk pogodowych.",
    "🌍 Jet stream to silne prądy powietrzne w wyższych warstwach atmosfery.",
    "🌈 Podwójna tęcza ma odwróconą kolejność kolorów.",
    "🌬️ Wiatr może przenosić pył przez kontynenty.",
    "🌦️ W rejonach równikowych codziennie pada deszcz po południu.",
    "🌩️ Dźwięk grzmotu zależy od odległości pioruna.",
    "🌫️ Mgła adwekcyjna powstaje, gdy ciepłe powietrze przesuwa się nad chłodnym gruntem.",
    "☁️ Chmury burzowe mogą osiągać wysokość 18 km.",
    "🧤 Niska wilgotność może powodować elektryzowanie się ubrań.",
    "🌡️ Pogoda wpływa na ciśnienie krwi i układ krążenia.",
    "🌀 Cyklon może utrzymywać się przez ponad tydzień.",
    "🧪 Modele pogodowe są aktualizowane co kilka godzin.",
    "🌧️ Średni czas opadu w Polsce to ok. 150 dni w roku.",
    "🌩️ Burza z wyładowaniami może mieć średnicę 100 km.",
    "📡 Pogoda ma wpływ na fale radiowe i komunikację satelitarną.",
    "🧊 Lód suchy to zamrożony dwutlenek węgla, nie występuje naturalnie.",
    "☀️ Indeks ciepła określa jak gorąco „czuje się” dana temperatura.",
    "🌪️ Tornada wodne nazywamy trąbami wodnymi.",
    "🌍 Pogoda może wpływać na migracje zwierząt.",
    "💨 Silny halny może przesuwać wagony kolejowe.",
    "🌈 Tęcza zawsze znajduje się naprzeciwko Słońca.",
    "🌡️ Zimne fronty przesuwają się szybciej niż ciepłe.",
    "🧊 Krupy śnieżne to forma zamarzniętych płatków z kroplami wody.",
    "☁️ Cirrus to najwyższe chmury, zwykle zwiastują zmianę pogody.",
    "🌦️ Średni czas życia chmury to ok. 10 minut.",
    "🌍 Zmiany klimatu zwiększają częstotliwość ekstremalnych zjawisk pogodowych.",
    "🌬️ Wiatry wiejące z lądu są zazwyczaj suche, z morza — wilgotne.",
    "🧭 Zjawiska pogodowe wpływały na historię ludzkości (np. upadek armii Napoleona).",
    "🌨️ W Japonii notuje się śnieg z kwiatowym pyłkiem — tzw. 'sakura snow'.",
    "🧪 Niektóre burze wytwarzają gamma błyski — tzw. TGF.",
    "🌡️ W Dolinie Śmierci temperatura potrafi utrzymywać się powyżej 50°C przez wiele dni.",
    "🌪️ Tornada pojawiały się również w Europie Środkowej — choć rzadko.",
    "📦 W logistyce pogoda decyduje o trasach dostaw i czasie dostawy.",
    "🌫️ Mgła lodowa bywa przyczyną wielkich karamboli na autostradach.",
    "🧊 Lód atmosferyczny może osadzać się na samolotach.",
    "🌬️ Prądy konwekcyjne tworzą chmury i burze.",
    "🌍 Pogoda w strefie umiarkowanej jest najbardziej zróżnicowana.",
    "🌧️ Deszcz pada w postaci różnych kropli — nie zawsze symetrycznych.",
    "🌈 Czasem można zobaczyć 'widmo Brockenu' — własny cień w tęczy.",
    "🌩️ Ziemia jest jedną z nielicznych planet z aktywną burzową atmosferą.",
    "☁️ Altostratus często zwiastuje nadchodzący deszcz.",
    "🧤 Podczas silnych mrozów temperatura odczuwalna może być niższa o 20°C.",
    "🌀 Niektóre cyklony mogą osiągnąć średnicę Polski!",
    "🌊 Zjawisko La Niña przynosi ochłodzenie i susze w wielu regionach.",
    "🌍 Na równiku dzień trwa niemal tyle samo przez cały rok.",
    "🌡️ Globalne ocieplenie zwiększa ilość pary wodnej w atmosferze.",
    "🌩️ Dźwięk grzmotu może rozchodzić się do 30 km od uderzenia.",
    "🧪 Modele klimatyczne przewidują zmiany setki lat do przodu.",
    "📡 Satelity obserwują Ziemię w wielu pasmach — podczerwień, UV i więcej.",
    "🌬️ Burze pyłowe z Sahary mogą wpływać na pogodę w Ameryce Południowej.",
    "☀️ Lato polarne to okres, gdy słońce nie zachodzi przez wiele dni.",
    "🌦️ 'Chmura soczewkowa' to znak silnego wiatru górskiego.",
    "🌨️ Sople mogą wskazywać kierunek wiatru podczas opadów.",
    "🧊 Lód morski topnieje szybciej niż kontynentalny.",
    "🌧️ Ciepłe fronty przynoszą łagodne, długotrwałe opady.",
    "🌍 Nawet małe zmiany w oceanach wpływają na globalną pogodę."
  ];

  CuriosityPage({super.key});

  @override
  Widget build(BuildContext context) {
    final random = Random();
    final fact = useState(facts[random.nextInt(facts.length)]);

    return Scaffold(
      floatingActionButton: Container(
        padding: EdgeInsetsGeometry.all(6),
        decoration: BoxDecoration(
          color: const Color.fromARGB(150, 170, 220, 240),
          borderRadius: BorderRadius.circular(20),
        ),
        child: TextButton(
            onPressed: () => fact.value = facts[random.nextInt(facts.length)],
            child: Text(
              "Losuj kolejną!",
              style: TextStyle(
                  color: Color.fromARGB(255, 15, 65, 100), fontSize: 20),
            )),
      ),
      appBar: AppBar(backgroundColor: const Color.fromARGB(150, 170, 220, 240)),
      body: SingleChildScrollView(
        child: AspectRatio(
          aspectRatio: MediaQuery.of(context).orientation
              == Orientation.portrait
              ? 0.7 : 2.8,
          child: Container(
            margin: MediaQuery.of(context).orientation
                == Orientation.portrait
                ? EdgeInsets.symmetric(horizontal: 20, vertical: 20)
                : EdgeInsets.symmetric(horizontal: 50, vertical: 20),
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: const Color.fromARGB(150, 170, 220, 240),
              borderRadius: BorderRadius.circular(20),
              boxShadow: [
                BoxShadow(
                  color: const Color.fromARGB(150, 170, 220, 240),
                  blurRadius: 10,
                  offset: const Offset(0, 4),
                ),
              ],
            ),
            child: Column(
              children: [
                Row(
                  children: [
                    Image.asset(
                      'assets/icons/light-bulb.png',
                      scale: 10,
                    ),
                    Text(
                      'Ciekawostka',
                      style: TextStyle(
                          fontSize: 40,
                          fontWeight: FontWeight.bold,
                        color: Color.fromARGB(255, 15, 65, 100)
                      ),
                    )
                  ],
                ),
                SizedBox(height: 20),
                Expanded(
                  child: Container(
                    padding: EdgeInsetsGeometry.all(20),
                    decoration: BoxDecoration(
                      color: Color.fromARGB(220, 255, 255, 255),
                      borderRadius: BorderRadius.circular(20),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.blue.shade100.withOpacity(0.4),
                          blurRadius: 10,
                          offset: const Offset(0, 4),
                        ),
                      ],
                    ),
                    child: Text(
                      fact.value,
                      style: const TextStyle(
                        fontSize: 30,
                        fontWeight: FontWeight.w500,
                          color: Color.fromARGB(255, 15, 65, 100)
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        )
      ),
    );
  }
}
